package chess.game.pkgfinal.project;

import chess.game.pkgfinal.project.models.MainFrame;
import javax.swing.JOptionPane;

/**
 * StartScreen.java - This is the Starting screen where the user is asked to  
 * press start button to play chess.
 *
 * @author Abhishek Shah
 * @since May-24-2022
 */
public class StartScreen extends javax.swing.JFrame {

    /**
     * Creates new form StartScreen
     */
    public StartScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        btnRules = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chess Game");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(600, 400));
        setName("frameStart"); // NOI18N
        setPreferredSize(new java.awt.Dimension(654, 350));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Snell Roundhand", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome to the Chess game");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 372, 51));

        btnStart.setBackground(new java.awt.Color(0, 9, 156));
        btnStart.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        btnStart.setForeground(new java.awt.Color(0, 9, 135));
        btnStart.setText("Start");
        btnStart.setOpaque(true);
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        getContentPane().add(btnStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        btnRules.setBackground(new java.awt.Color(0, 9, 156));
        btnRules.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        btnRules.setForeground(new java.awt.Color(0, 9, 135));
        btnRules.setText("Rules");
        btnRules.setOpaque(true);
        btnRules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRulesActionPerformed(evt);
            }
        });
        getContentPane().add(btnRules, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 133, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chessBackground.jpeg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        MainFrame game = new MainFrame();  // Navigates to chess game
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnRulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRulesActionPerformed
        JOptionPane.showMessageDialog(null, 
                "Pawn: -> moves forward only one square unless it " +
                         "is that pawn’s first move. \n\n" +
                "Rook: -> moves forward, backward or sideways, but " +
                         "cannot move diagonally.\n\n" +
                "Bishop: -> moves only diagonally in any directions.\n\n" +
                "Knight: -> moves in L-Shape directions.\n\n" +
                "Queen: -> moves in any square in all direction. \n\n" + 
                "King: -> can move only one step in any direction.",
                "Chess Rules",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnRulesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRules;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
